
import type {Metadata} from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { SolarHeader } from '@/components/solar-template/solar-header';
import { SolarFooter } from '@/components/solar-template/solar-footer';
import { WhatsappButton } from '@/components/ui/whatsapp-button';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const companyName = 'Radiant Solar Solutions';
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} antialiased bg-background text-foreground`}>
        <SolarHeader companyName={companyName} />
        {children}
        <WhatsappButton phoneNumber="2347045396856" />
        <SolarFooter companyName={companyName} />
      </body>
    </html>
  );
}
